insert into Client (name, last_name, phone) values ('Nola', 'Collumbine', '2386566503');
insert into Client (name, last_name, phone) values ('Marleen', 'Jeavons', '6653128448');
insert into Client (name, last_name, phone) values ('Cameron', 'Glenton', '4237319282');
insert into Client (name, last_name, phone) values ('Lindy', 'Alger', '3898255792');
insert into Worker (name, last_name, position) values ('Ryon', 'Insull', 'Owner');
insert into Worker (name, last_name, position) values ('Chaddy', 'Cona', 'Mechanic');
insert into Worker (name, last_name, position) values ('Elfrida', 'Dayborne', 'Spraying');
insert into Worker (name, last_name, position) values ('Earle', 'Ebbers', 'Mechanic');
insert into Car (mark, type, year, vin, color, client_id, worker_id) values ('Lexus', 'GS', 1998, 'KNADH4A32A6350851', 'Khaki', 1, 1);
insert into Car (mark, type, year, vin, color, client_id, worker_id) values ('Audi', 'S8', 2006, 'SALVN2BG0FH316384', 'Maroon', 2, 2);
insert into Car (mark, type, year, vin, color, client_id, worker_id) values ('Mitsubishi', 'Galant', 1993, 'JN1BJ0HPXDM756721', 'Puce', 3, 3);
insert into Car (mark, type, year, vin, color, client_id, worker_id) values ('Dodge', 'Charger', 2011, 'WBAWV135X9P471485', 'Pink', 1, 4);
insert into Car (mark, type, year, vin, color, client_id, worker_id) values ('Ford', 'Explorer', 2003, 'YV1902AH4E1761925', 'Aquamarine', 2, 1);
insert into Car (mark, type, year, vin, color, client_id, worker_id) values ('Lamborghini', 'Gallardo', 2009, 'WAUKH78E48A659714', 'Turquoise', 3, 2);
insert into Car (mark, type, year, vin, color, client_id, worker_id) values ('Hyundai', 'Sonata', 2011, 'JM1GJ1T64F1362305', 'Puce', 4, 3);
insert into Car (mark, type, year, vin, color, client_id, worker_id) values ('Porsche', 'Boxster', 2008, '1G6AC5S34F0855845', 'Red', 2, 4);
insert into Car (mark, type, year, vin, color, client_id, worker_id) values ('Audi', 'S8', 2003, '1GD01ZCG7EF748447', 'Red', 4, 1);
insert into Car (mark, type, year, vin, color, client_id, worker_id) values ('Mazda', 'MX-3', 1994, 'WAUNF98P08A008726', 'Green', 1, 2);
insert into Car (mark, type, year, vin, color, client_id, worker_id) values ('Mazda', 'RX-7', 1986, '2C3CDXGJ2EH662758', 'Puce', 4, 3);
insert into Car (mark, type, year, vin, color, client_id, worker_id) values ('GMC', '1500', 1997, 'WBAPH5C58BA887711', 'Blue', 3, 4);
insert into Car (mark, type, year, vin, color, client_id, worker_id) values ('Lexus', 'RX', 2000, '1G6DG577X90030698', 'Teal', 4, 1);
insert into Car (mark, type, year, vin, color, client_id, worker_id) values ('Pontiac', 'Grand Prix', 2006, '5NPDH4AE1EH020988', 'Maroon', 1, 2);
insert into Car (mark, type, year, vin, color, client_id, worker_id) values ('Nissan', 'Pathfinder', 2010, '1C4SDJCT0DC907263', 'Orange', 2, 3);
insert into Car (mark, type, year, vin, color, client_id, worker_id) values ('Ford', 'Crown Victoria', 2007, 'WAUFFAFL0AN553555', 'Violet', 3, 4);
insert into Car (mark, type, year, vin, color, client_id, worker_id) values ('Volkswagen', 'Eurovan', 1995, 'WA1LMAFE8BD643938', 'Pink', 1, 2);
insert into Car (mark, type, year, vin, color, client_id, worker_id) values ('Chevrolet', 'G-Series G20', 1994, 'WP0AA2A95BS657569', 'Crimson', 2, 3);
insert into Car (mark, type, year, vin, color, client_id, worker_id) values ('Kia', 'Amanti', 2009, '5GAKVBKD9FJ001979', 'Green', 3, 4);
insert into WORK_CAR (car_id, worker_id) values (19,2);
insert into WORK_CAR (car_id, worker_id) values (18,3);
insert into WORK_CAR (car_id, worker_id) values (16,4);
insert into WORK_CAR (car_id, worker_id) values (15,1);
insert into WORK_CAR (car_id, worker_id) values (14,3);
insert into WORK_CAR (car_id, worker_id) values (13,2);
insert into WORK_CAR (car_id, worker_id) values (12,2);
insert into WORK_CAR (car_id, worker_id) values (11,2);
insert into WORK_CAR (car_id, worker_id) values (10,1);
insert into WORK_CAR (car_id, worker_id) values (9,3);
insert into WORK_CAR (car_id, worker_id) values (8,3);
insert into WORK_CAR (car_id, worker_id) values (7,3);
insert into WORK_CAR (car_id, worker_id) values (6,4);
insert into WORK_CAR (car_id, worker_id) values (5,4);
insert into WORK_CAR (car_id, worker_id) values (4,2);
insert into WORK_CAR (car_id, worker_id) values (3,2);
insert into WORK_CAR (car_id, worker_id) values (2,3);
insert into WORK_CAR (car_id, worker_id) values (1,4);
insert into Car (mark, type, year, vin, color, client_id, worker_id) values ('Kia', 'Amanti', 2009, '5GAKVBKD9FJ001970', 'Green', 2, 4);